targets:
  $default:
    builders:
      openapi_generator_flutter:
        enabled: true
        options:
          run_generator: true
          input_folder: "open_api_files"
          output_folder: "lib/generated"
          input_urls: ["open_api_files/petstore.yaml"]
builders:
  openapi_generator_flutter:
    import: "package:openapi_generator_flutter/builder.dart"
    builder_factories: ["openapiBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source 