name: openapi_generator_flutter
description: OpenAPI (Swagger) client generator for Flutter applications
version: 1.0.1
repository: https://github.com/taskcrypto/openapi_generator_flutter
homepage: https://github.com/taskcrypto/openapi_generator_flutter
issue_tracker: https://github.com/taskcrypto/openapi_generator_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter: #Default
    sdk: flutter

  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  code_builder: ^4.9.0
  yaml: ^3.1.2
  json_annotation: ^4.9.0
  http: ^1.2.0
  path: ^1.8.3
  args: ^2.4.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0

flutter:
  uses-material-design: true

executables:
  generate: generate
