name: openapi_generator_flutter
description: OpenAPI仕様からDartのAPIクライアントとモデルを生成するツール
version: 1.1.5
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  build_resolvers: ^2.4.1
  code_builder: ^4.8.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  retrofit: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^5.0.0
  retrofit_generator: ^8.1.0
  test: ^1.24.9

flutter:
  uses-material-design: true

builders:
  openapi_generator_flutter:
    import: "package:openapi_generator_flutter/builder.dart"
    builder_factories: ["openapiBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source