openapi: 3.1.0
info:
  title: サンプルAPI
  version: 1.0.0
  description: これはサンプルのOpenAPI仕様です。

paths:
  /auth/token:
    post:
      tags:
        - auth
      summary: トークンを取得
      operationId: getToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestToken'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseToken'

components:
  schemas:
    RequestToken:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: ユーザー名
        password:
          type: string
          description: パスワード

    ResponseToken:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: アクセストークン 